In [3]:
 from citipy import citipy

# Dependencies
import requests
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from config import weather_api_key
import time

In [4]:
# Create a set of random latitude and longitude combinations.
lats = np.random.uniform(low=-90.000, high=90.000, size=2000)
lngs = np.random.uniform(low=-180.000, high=180.000, size=2000)
lat_lngs = zip(lats, lngs)

In [5]:
coordinates = list(lat_lngs)
coordinates[0:5]

[(-54.852101790748684, -56.151613540677616),
 (4.629918725181824, -22.77606667593122),
 (74.45875699187283, -100.71852626250984),
 (14.303201487352425, 89.6774353892203),
 (-52.5988044277575, -36.213425455284124)]

In [6]:
 cities = []

for coord in coordinates:
    lat = coord[0]
    long = coord[1]
    
    city = citipy.nearest_city(lat, long)
    city_name = city.city_name
    
    if city_name not in cities:
        cities.append(city_name)
        
print(len(cities))

772

In [7]:
# init lists
longs = []
lats = []
temps = []
pressures = []
humids = []
cities_df = []
countries = []

base_url = "http://api.openweathermap.org/data/2.5/weather"

for city in cities[0:50]:
    # Build query URL
    print(city)
    query_url = f"{base_url}?appid={weather_api_key}&q={city}&units=imperial"
    
    response = requests.get(query_url)

    if (response.status_code == 200):
        data = response.json()
        
        # data parsing
        try:
            long = data["coord"]["lon"]
            lat = data["coord"]["lat"]
            temp = data["main"]["temp"]
            pressure = data["main"]["pressure"]
            humid = data["main"]["humidity"]
            city_p = data["name"]
            country = data["sys"]["country"]

            # append to lists
            longs.append(long)
            lats.append(lat)
            temps.append(temp)
            pressures.append(pressure)
            humids.append(humid)
            cities_df.append(city_p)
            countries.append(country)
        except Exception as e:
            print(e)
            
            # append defaults to lists
            longs.append(np.nan)
            lats.append(np.nan)
            temps.append(np.nan)
            pressures.append(np.nan)
            humids.append(np.nan)
            cities_df.append(city)
            countries.append("")
    else:
        print(response.status_code)
        print(response.text)
        
    # sleep for one second
    time.sleep(1)
        
# build dataframe
df = pd.DataFrame()
df["City"] = cities_df
df["Countries"] = countries
df["Temp"] = temps
df["Humidity"] = humids
df["Pressure"] = pressures
df["Latitude"] = lats
df["Longitude"] = longs

df

ushuaia
bubaque
yellowknife
port blair
chuy
saskylakh
anloga
ancud
fairbanks
avarua
tiksi
funtua
albany
doka
rikitea
ostrovnoy
busselton
cidreira
hokitika
thompson
leningradskiy
hofn
chokurdakh
sibolga
sakaiminato
markova
kapaa
yaan
provideniya
mayya
halifax
moree
puerto ayora
east london
grand river south east
404
{"cod":"404","message":"city not found"}
klamath falls
northam
tselinnoye
tsihombe
404
{"cod":"404","message":"city not found"}
jamestown
santa eulalia del rio
404
{"cod":"404","message":"city not found"}
grindavik
huarmey
qianjiang
progreso
bluff
nikolskoye
husavik
sitka
hilo

             City Countries   Temp  Humidity  Pressure  Latitude  Longitude
0         Ushuaia        AR  42.46        81       991  -54.8000   -68.3000
1         Bubaque        GW  76.50        77      1011   11.2833   -15.8333
2     Yellowknife        CA  27.12        74      1000   62.4560  -114.3525
3      Port Blair        IN  86.04        79      1006   11.6667    92.7500
4            Chui        UY  56.34        92      1021  -33.6971   -53.4616
5       Saskylakh        RU  13.55        89      1012   71.9167   114.0833
6          Anloga        GH  82.27        81      1009    5.7947     0.8973
7           Ancud        CL  47.88        93      1026  -41.8697   -73.8203
8       Fairbanks        US  44.74        52      1014   64.8378  -147.7164
9          Avarua        CK  84.25        79      1013  -21.2078  -159.7750
10          Tiksi        RU  16.07        82      1005   71.6872   128.8694
11         Funtua        NG  78.60        57      1009   11.5233     7.3081
12         Albany        US  46.31        57      1025   42.6001   -73.9662
13           Doka        SD  83.50        49      1007   13.5167    35.7667
14        Rikitea        PF  76.28        75      1017  -23.1203  -134.9692
15      Ostrovnoy        RU  30.15        79      1016   68.0531    39.5131
16      Busselton        AU  66.54        61      1020  -33.6500   115.3333
17       Cidreira        BR  65.10        83      1021  -30.1811   -50.2056
18       Hokitika        NZ  60.62        75      1014  -42.7167   170.9667
19       Thompson        CA  55.56        41       998   55.7435   -97.8558
20  Leningradskiy        RU  29.62        90      1012   69.3833   178.4167
21           Hofn        IS  44.19        91      1001   64.2539   -15.2082
22     Chokurdakh        RU  23.74        87      1003   70.6333   147.9167
23        Sibolga        ID  86.04        65      1010    1.7427    98.7792
24    Sakaiminato        JP  58.98        67      1018   35.5500   133.2333
25        Markova        UA  48.47        82      1024   48.6758    24.4138
26          Kapaa        US  77.43        80      1019   22.0752  -159.3190
27           Yaan        NG  78.49        80      1009    7.3833     8.5667
28    Provideniya        RU  33.30        93      1008   64.3833  -173.3000
29          Mayya        RU  43.32        67      1005   61.7333   130.2811
30        Halifax        CA  35.33        76      1026   44.6453   -63.5724
31          Moree        AU  75.22        43      1022  -29.4667   149.8500
32   Puerto Ayora        EC  71.49        91      1013   -0.7393   -90.3518
33    East London        ZA  61.09        77      1020  -33.0153    27.9116
34  Klamath Falls        US  32.83        75       969   42.2249  -121.7817
35        Northam        GB  48.85        76      1024   51.0333    -4.2167
36     Tselinnoye        RU  46.47        39      1030   53.0833    85.6667
37      Jamestown        US  56.44        33      1020   42.0970   -79.2353
38      Grindavik        IS  46.87        93       995   63.8424   -22.4338
39        Huarmey        PE  64.89        92      1014  -10.0681   -78.1522
40      Qianjiang        CN  66.43        59      1016   30.4151   112.8859
41       Progreso        MX  91.51        72      1009   21.2833   -89.6667
42          Bluff        NZ  56.80        79      1016  -46.6000   168.3333
43     Nikolskoye        RU  31.91        81      1025   59.7035    30.7861
44        Husavik        IS  42.85        89       998   66.0449   -17.3389
45          Sitka        US  51.69        66      1011   57.0531  -135.3300
46           Hilo        US  76.42        78      1019   19.7297  -155.0900

In [8]:
 df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47 entries, 0 to 46
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   City       47 non-null     object
 1   Countries  47 non-null     object
 2   Temp       47 non-null     float64
 3   Humidity   47 non-null     int64
 4   Pressure   47 non-null     int64
 5   Latitude   47 non-null     float64
 6   Longitude  47 non-null     float64
dtypes: float64(3), int64(2), object(2)
memory usage: 2.7+ KB

In [9]:
df.to_csv("output.csv", index=True)